name: Build Android Apps
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.0
      - name: Build Student APK
        run: ./gradlew :app-student:assembleDebug
      - name: Build Teacher APK
        run: ./gradlew :app-teacher:assembleDebug
      - name: Upload Student APK
        uses: actions/upload-artifact@v4
        with:
          name: Student-App
          path: app-student/build/outputs/apk/debug/app-student-debug.apk
      - name: Upload Teacher APK
        uses: actions/upload-artifact@v4
        with:
          name: Teacher-App
          path: app-teacher/build/outputs/apk/debug/app-teacher-debug.apk
